BIN=pwmig
DIRS=
PF=pwmig.pf

#MAN1=pwmig.1
cxxflags=-g -DNO_ANTELOPE
#cxxflags= -DNO_ANTELOPE -O2
ldlibs=-lstock -lcoords -lpwmig -lseispp -lgclgrid -lcoords -lperf -lm -lstock
DBX=-g

include $(PWMIGMAKE) 
OBJS= pwmig.o \
decimate.o \
mdutils.o \
ray_transformation_operator.o \
raygrid.o
# include dependencies
mdutils.cc : pwmig.h
pwmig.cc : pwmig.h
ray_transformation_operator.cc : pwmig.h
raygrid.cc : pwmig.h
$(BIN) : $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDFLAGS) $(LDLIBS)
