#!/bin/bash
#Get gps mean from postion program, designed for mass-processing of log files.
#This program calls the antelope contributed program: position, see its man page for more information.
#* USAGE: get_gps_mean.sh -F|f logfilelist|logfile [-p rt2ms_pf]
#* Make sure you have 'position' installed on your computer.
#	-F: file list
#	-f: single log file name
#	-p: followed by the same pf used in rt2ms for DAS & station pairing.
#   ** logfile name follows the format generated by rt2ms, e.g.,
# 	2013.176.14.12.56.9254.log.

# By Xiaotao Yang on Dec 29, 2013

if [ $# -lt 2 ] || [ $# -eq 3 ] || [ $# -gt 4 ]
	then
		echo "** USAGE: get_gps_mean.sh -F|f logfilelist|logfile [-p rt2ms_pf]"
		echo "** Make sure you have 'position' installed on your computer."
		echo "-F: file list"
		echo "-f: single log file name"
		echo "-p: followed by the same pf used in rt2ms for DAS & station pairing."
		echo "NOTE: logfile name follows the format generated by rt2ms, e.g., 2013.176.14.12.56.9254.log."
		exit 1
fi

pflag=0  		# flag for rt2ms parameter file.
if [ $# -eq 4 ] && [ $3 == "-p" ]; then pflag=1; fi
#echo $pflag

#for a list of log files.
if [ $1 == "-F" ]; then

	flist=$2

	if [ $pflag == 1 ]; then 
		pf=$4
		echo "DAS	station		lat	lon	 elevation"
	else
		echo "DAS	lat     lon      elevation"
	fi

	for f in `cat $flist`
	do
		das=`echo $f | sed -e 's/\./ /g' | awk '{print $6}'`
		elev=`position $f | grep Elevation | awk '{print $3}'`
		stmp=`position $f | grep New | grep Average | sed -e 's/,/ /g' `
		lat=` echo $stmp | awk '{print $4}'` 
		lon=` echo $stmp | awk '{print $5}'`
	
		if [ $pflag == 1 ]; then 
        		sta=`grep $das $pf | head -1 | sed -e 's/;/ /g' | awk '{print $5}'`
        		#echo "DAS       station         lat     lon      elevation"
			echo $das	$sta	$lat	$lon	$elev
		else
        		#echo "DAS         lat     lon      elevation"
			echo $das	$lat    $lon    $elev
		fi
		#echo $lat $lon
	done

# for a single log file.
elif [ $1 == "-f" ]; then
	f=$2	
	if [ $pflag == 1 ]; then
        	pf=$4
        	echo "DAS       station         lat     lon      elevation"
	else
        	echo "DAS       lat     lon      elevation"
	fi

	das=`echo $f | sed -e 's/\./ /g' | awk '{print $6}'`
	elev=`position $f | grep Elevation | awk '{print $3}'`
	stmp=`position $f | grep New | grep Average | sed -e 's/,/ /g' `
	lat=` echo $stmp | awk '{print $4}'`
	lon=` echo $stmp | awk '{print $5}'`

	if [ $pflag == 1 ]; then
        	sta=`grep $das $pf | head -1 | sed -e 's/;/ /g' | awk '{print $5}'`
                #echo "DAS       station         lat     lon      elevation"
        	echo $das       $sta    $lat    $lon    $elev
	else
        	#echo "DAS         lat     lon      elevation"
        	echo $das       $lat    $lon    $elev
	fi

else
	echo "** ERROR: Wrong options for the program."
	exit 1
fi
